### ISSUE TITLE
Getting compilation error due to solidity version on remix

### ISSUE THREAD

**Issue by Dentrax** [balancer-labs/balancer-v2-monorepo#1106]
Just tried to implement `v2-solidity-utils` library on a custom contract and got following compilation error on remix.ethereum.org:

```solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.9;

import "@balancer-labs/v2-solidity-utils/contracts/math/LogExpMath.sol";
```

```
ParserError: Source file requires different compiler version (current compiler is 0.8.9+commit.e5eed63a.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version
  --> @balancer-labs/v2-solidity-utils/contracts/math/LogExpMath.sol:15:1:
   |
15 | pragma solidity ^0.7.0;
   | ^^^^^^^^^^^^^^^^^^^^^^^
```

Tried to set version to `^0.8.9` but no luck. Any ideas? 🤔

**Comment by nventuro** [comment]
Hi @Dentrax! Balancer contracts are compiled with solc 0.7.1, which is why you're getting that error. You could port them into 0.8, starting by changing the `pragma solidity` line to read `^0.8.0` instead of `^0.7.0`, as well as any other changes you might find relevant, the most obvious one being usage of checked arithmetic.

We're looking into porting our code to 0.8 soon, but that has not yet happened.

**Comment by ZeroPointLabs** [comment]
> Hi @Dentrax! Balancer contracts are compiled with solc 0.7.1, which is why you're getting that error. You could port them into 0.8, starting by changing the `pragma solidity` line to read `^0.8.0` instead of `^0.7.0`, as well as any other changes you might find relevant, the most obvious one being usage of checked arithmetic. Alternatively, you could compile with 0.7.1.
> 
> We're looking into porting our code to 0.8 soon, but that has not yet happened.

and  a year later nope

**Comment by nventuro** [comment]
The interfaces are available for both 0.7 and 0.8. There's no improvement that I'm aware of in 0.8 that'd make the switch worthwhile. We'd actually likely run into performance regressions due to https://github.com/ethereum/solidity/issues/10698.
